-- Production migration-history marker (055 meeting_briefing_deliveries).
-- Its schema effect is already included in 00000000000000_production_schema_baseline.sql.
-- Keep this file as a no-op so clean environments and the production ledger remain aligned.
