-- Production migration-history marker (20260513143104 add_project_manager_slack_id_to_projects).
-- Its schema effect is already included in 00000000000000_production_schema_baseline.sql.
-- Keep this file as a no-op so clean environments and the production ledger remain aligned.
