-- Production migration-history marker (20260821031711 index_daily_hours_reminders_check_in_id).
-- Its schema effect is already included in 00000000000000_production_schema_baseline.sql.
-- Keep this file as a no-op so clean environments and the production ledger remain aligned.
